print("###############################")
print("#                             #")
print("# Muhammad Adh-Dhiya'Us Salim #")
print("#       2310817210022         #")
print("#                             #")
print("###############################")